spring.application.name=testeDynamoDB

server.port=8082
server.servlet.context-path=/testeDynamoDB

# Configuracoes do DynamoDB
aws.dynamodb.accessKeyId=${AWS_ACCESSKEY}
aws.dynamodb.secretKey=${AWS_SECRETKEY}
aws.dynamodb.region=us-east-1
aws.dynamodb.endpoint=http://localhost:8000

app.local=true



